[build]
cmd = "task build OUT=./tmp/main"
delay = 1000
include_dir = ["cmd", "internal"]
exclude_dir = ["cmd/web/static"]
exclude_regex = ["_test.go", "_templ.go", "generated.go"]

[log]
main_only = true

[misc]
clean_on_exit = true
