[build]
bin = "./dist/bookfeed"
cmd = "task build"
exclude_dir = ["cmd/web/static", "tmp", "testdata", "node_modules"]
exclude_regex = ["_test.go", "_templ.go", "generated.go"]
include_ext = ["go", "tmpl", "templ", "css", "js"]
