version: "2"
linters:
  default: standard
  enable:
    - contextcheck
    - gocognit
    - goconst
    - tagalign
    - goprintffuncname
    - zerologlint
formatters:
  enable:
    - gofumpt
    - golines
