version: 2
before:
  hooks:
    - go generate ./...
    - go mod tidy

builds:
  - binary: "{{ .ProjectName }}"
    main: ./cmd/bookfeed
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
release:
  prerelease: auto

universal_binaries:
  - replace: true

archives:
  - name_template: >
      {{- .ProjectName }}_{{- .Version }}_{{- title .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        formats:
          - zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md

kos:
  - id: bookfeed
    user: 1000:1000
    repositories:
      - ghcr.io/robbrazier/{{ .ProjectName }}
      - "{{ .GitUrl.Owner }}/{{ .ProjectName }}"
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      # - latest
      - "{{.Tag}}"
      - "v{{.Major}}"
      - "v{{.Major}}.{{.Minor}}"
      - "{{if not .Prerelease}}stable{{end}}"

checksum:
  name_template: "checksums.txt"
