version: "3"

dotenv:
  - .env

env:
  CGO_ENABLED: 0

tasks:
  download-schema:
    cmd: 'go run github.com/benweint/gquil/cmd/gquil@latest introspection generate-sdl https://api.hardcover.app/v1/graphql -H "Authorization: {{ .HARDCOVER_TOKEN }}" > internal/schema/schema.gql'
    requires:
      vars: [HARDCOVER_TOKEN]

  install-bun:
    internal: true
    prompt: This project needs the bun package manager - Install (via npm)?
    cmd: npm install -g bun
    status:
      - which bun

  install:
    deps:
      - install-bun
    cmd: bun install
    sources:
      - package.json
      - bun.lock
    generates:
      - node_modules/**/*

  clean:
    cmd: rm -r {{ .ROOT_DIR }}/dist
    status:
      - "! test -d {{ .ROOT_DIR }}/dist"

  generate:
    deps:
      - install
    cmd: go generate ./...

  build:
    deps:
      - generate
    vars:
      OUT: '{{ .OUT | default "dist/bookfeed" }}'
    cmd: go build -o {{ .OUT }} ./cmd/api

  run:
    cmd: go run cmd/api/main.go

  dev:
    vars:
      AIR_CMD:
        sh: which air 2>/dev/null || echo "go run github.com/air-verse/air@latest"
    cmd: '{{ .AIR_CMD }}'

  test:
    cmd: go test ./... -v
