version: "3"

dotenv:
  - .env

env:
  CGO_ENABLED: 0

vars:
  RUN_COMMAND: "{{ if .SECRETS_COMMAND }}{{ .SECRETS_COMMAND }} -- {{end}}"

tasks:
  download-schema:
    cmd: 'go run github.com/benweint/gquil/cmd/gquil@latest introspection generate-sdl https://api.hardcover.app/v1/graphql -H "Authorization: {{ .HARDCOVER_TOKEN }}" > internal/schema/schema.gql'
    requires:
      vars: [HARDCOVER_TOKEN]

  install-bun:
    internal: true
    prompt: This project needs the bun package manager - Install (via npm)?
    cmd: npm install -g bun
    status:
      - which bun

  install:
    deps:
      - install-bun
    cmd: bun install
    sources:
      - package.json
      - bun.lock
    generates:
      - node_modules/**/*

  clean:
    cmd: rm -r {{ .ROOT_DIR }}/dist
    status:
      - "! test -d {{ .ROOT_DIR }}/dist"

  generate:
    deps:
      - install
    cmd: go generate ./...

  build:
    deps:
      - generate
    vars:
      OUT: '{{ .OUT | default "dist/bookfeed" }}'
    cmd: go build -o {{ .OUT }} ./cmd/api

  run:
    cmd: "{{ .RUN_COMMAND }}go run cmd/api/main.go"

  dev:
    vars:
      AIR_CMD:
        sh: which air 2>/dev/null || echo "go run github.com/air-verse/air@latest"
    cmd: "{{ .RUN_COMMAND }}{{ .AIR_CMD }}"

  test:
    cmd: go test ./... -v

  templui:
    cmd: go run github.com/templui/templui/cmd/templui@latest {{.CLI_ARGS}}

  templui:update:
    vars:
      COMPONENTS:
        sh: "ls cmd/web/components | xargs echo"
    cmds:
      - task: templui
        vars:
          CLI_ARGS: "-f add {{ .COMPONENTS }}"
