version: "3"

dotenv:
  - .env

env:
  CGO_ENABLED: 0

tasks:
  download-schema:
    cmds:
      - "go tool gquil introspection generate-sdl https://api.hardcover.app/v1/graphql -H 'Authorization: {{ .HARDCOVER_TOKEN }}' > internal/schema/schema.gql"
    requires:
      vars: [HARDCOVER_TOKEN]

  install-bun:
    internal: true
    cmd: npm install -g bun
    status:
      - which bun

  install:
    deps:
      - install-bun
    cmd: bun install
    sources:
      - package.json
      - bun.lock
    generates:
      - node_modules/**/*

  clean:
    cmd: rm -r {{ .ROOT_DIR }}/dist
    status:
      - "! test -d {{ .ROOT_DIR }}/dist"

  templui:
    cmd: go tool templui {{.CLI_ARGS}}

  generate:
    deps:
      - install
    cmd: go generate ./...

  build:
    deps:
      - generate
    cmd: go build -o dist/bookfeed ./cmd/api

  run:
    cmd: go run cmd/api/main.go

  install-air:
    internal: true
    cmd: go install github.com/air-verse/air@latest
    status:
      - which air

  dev:
    deps:
      - install-air
    cmd: air

  test:
    cmd: go test ./... -v
