# Name of your application. Used to uniquely configure containers.
# <% require "dotenv"; Dotenv.load(".env") %>
service: hardcover-rss

# Name of the container image.
image: robbrazier/hardcover-rss

# Deploy to these servers.
servers:
  web: <%= ENV.fetch('SERVER_IPS').split(' ') %>

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: hardcover-rss.robbrazier.com
  app_port: 8080

# Credentials for your image host.
registry:
  server: ghcr.io
  username: robbrazier

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  # Pass in additional build args needed for your Dockerfile.
  # args:
  #   RUBY_VERSION: <%= ENV["RBENV_VERSION"] || ENV["rvm_ruby_string"] || "#{RUBY_ENGINE}-#{RUBY_ENGINE_VERSION}" %>

env:
  clear:
    PORT: 8080
  secret:
    - HARDCOVER_TOKEN

ssh:
  user: deploy
