fragment Book on books {
  id
  slug
  title
  releaseDate: release_date
  headline
  description
  # @genqlient(bind: "[]github.com/RobBrazier/bookfeed/internal/hardcover.BookGenre")
  genres: cached_tags(path: "Genre")
  # @genqlient(bind: "[]github.com/RobBrazier/bookfeed/internal/hardcover.BookContributor")
  contributions: cached_contributors
  compilation
  # @genqlient(bind: "github.com/RobBrazier/bookfeed/internal/hardcover.BookImage")
  image: cached_image
  # @genqlient(bind: "github.com/RobBrazier/bookfeed/internal/hardcover.BookFeaturedSeries")
  featuredSeries: cached_featured_series
}
