fragment Book on books {
  id
  slug
  title
  releaseDate: release_date
  headline
  description
  # @genqlient(bind: "[]github.com/RobBrazier/bookfeed/internal/hardcover.BookGenre")
  genres: cached_tags(path: "Genre")
  contributions {
    author {
      name
    }
  }
  compilation
  # @genqlient(bind: "github.com/RobBrazier/bookfeed/internal/hardcover.BookImage")
  image: cached_image
  # @genqlient(bind: "github.com/RobBrazier/bookfeed/internal/hardcover.BookFeaturedSeries")
  featuredSeries: cached_featured_series
}

query RecentReleases($now: date, $earliest: date) {
  # @genqlient(flatten: true)
  books(
    order_by: {users_count: desc_nulls_last}
    where: {
      release_date: {_lte: $now, _gte: $earliest}
    }
    limit: 25
  ) {
    ...Book
  }
}

query RecentSeriesReleases($now: date, $earliest: date, $slug: [String!], $compilations: Boolean = false) {
  series(where: { slug: {_in: $slug} }) {
    name
    slug
  }
  bookSeries: book_series(
    where: {
      series: {
        slug: {_in: $slug}
      },
      book: {
        release_date: {_lte: $now, _gte: $earliest},
        book_mappings: {id: {_is_null: false}}
        compilation: {
          _in: [$compilations, false]
        }
      }
    }
    order_by: {book: {release_date: desc_nulls_last}}
    limit: 25
  ) {
    series {
      name
    }
    # @genqlient(flatten: true)
    book {
      ...Book
    }
  }
}

query RecentAuthorReleases($now: date, $earliest: date, $slug: [String!], $compilations: Boolean = false) {
  authors(where: {slug: {_in: $slug}}) {
    name
    slug
    contributions(
      where: {
        contribution: {_is_null: true}, # only get Authors
        book: {
          release_date: {_lte: $now, _gte: $earliest},
          book_mappings: {id: {_is_null: false}},
          compilation: {
            _in: [$compilations, false]
          }
        }
      }
      order_by: {book: {release_date: desc_nulls_last}}
      limit: 25
    ) {
      author {
        name
      }
      # @genqlient(flatten: true)
      book {
        ...Book
      }
    }
  }
}

query UserInterests($username: citext, $earliest: date) {
  users(where: {username: {_eq: $username}}) {
    username
  }
  userBooks: user_books(
    where: { 
      user: { username: {_eq: $username}}, 
      status_id: {_eq: 3}, # status.READ
      last_read_date: { _gt: $earliest}
    }
  ) {
    book {
      slug
      # @genqlient(bind: "[]github.com/RobBrazier/bookfeed/internal/hardcover.BookContributor")
      contributors: cached_contributors
      # @genqlient(bind: "github.com/RobBrazier/bookfeed/internal/hardcover.BookFeaturedSeries")
      featuredSeries: cached_featured_series
    }
  }
}
