name: deploy

on:
  workflow_call:
    secrets:
      DOPPLER_SECRET_DEV:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      SERVER_IPS:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubicloud-standard-2
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
      - uses: ruby/setup-ruby@1a615958ad9d422dd932dc1d5823942ee002799f # v1.227.0
        with:
          ruby-version: "3.4"
      - run: |
          gem install kamal
      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - uses: crazy-max/ghaction-github-runtime@b3a9207c0e1ef41f4cf215303c976869d0c2c1c4 # v3.0.0
      - name: Setup doppler cli
        run: |
          echo "${{ secrets.DOPPLER_SECRET_DEV }}" | doppler configure set token --scope /
      - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: kamal deploy
        env:
          SERVER_IPS: ${{ secrets.SERVER_IPS }}
          PROXY_HOSTS: ${{ vars.PROXY_HOSTS }}
