name: Go Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubicloud-standard-2
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
      - name: Build
        run: task build
      - name: Test
        run: task test

  deploy:
    needs: build
    if: github.ref_name == 'main'
    uses: ./.github/workflows/deploy.yml
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_IPS: ${{ secrets.SERVER_IPS }}
      HARDCOVER_TOKEN: ${{ secrets.HARDCOVER_TOKEN }}
