name: Go-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubicloud-standard-2
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Build
        run: task build
      - name: Test
        run: task test
